logging:
  pattern:
    console: log@%clr(%d{mm:ss SSS}){blue}%clr(-%5p){red} [%logger] %clr(%m){magenta}%n
  level:
    com.spoom: debug
    org.springframework: WARN
    org.hibernate: WARN


# tomcat port
server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8087
  connection-timeout: 5000ms

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.spoom.nymph.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
